package com.zekrom_64.ze.bullet3.dynamics;

public enum BTDynamicsWorldType {

	SIMPLE_DYNAMICS_WORLD,
	DISCRETE_DYNAMICS_WORLD,
	CONTINUOUS_DYNAMICS_WORLD,
	SOFT_RIGID_DYNAMICS_WORLD,
	GPU_DYNAMICS_WORLD,
	SOFT_MULTIBODY_DYNAMICS_WORLD
	
}
