package com.zekrom_64.ze.gl.shader;

import com.zekrom_64.ze.base.err.ZEngineException;

@Deprecated
/** An exception generated by an error in the GLSL compiler.
 * 
 * @author Zekrom_64
 *
 */
public class GLSLCompilerException extends ZEngineException {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2832712413351435224L;
	public final int shader;
	public GLSLCompilerException(String log, int shader) {
		super("Failed to compile shader, dumping log:\r\n\r\n" + log + "\r\n");
		this.shader = shader;
	}
	
}
