/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zekrom_64_ze_nat_ZEArrayMemory */

#ifndef _Included_com_zekrom_64_ze_nat_ZEArrayMemory
#define _Included_com_zekrom_64_ze_nat_ZEArrayMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: (Ljava/lang/Object;Z)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map__Ljava_lang_Object_2Z
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([ZZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3ZZ
  (JNIEnv *, jclass, jbooleanArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([BZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3BZ
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([SZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3SZ
  (JNIEnv *, jclass, jshortArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([CZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3CZ
  (JNIEnv *, jclass, jcharArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([IZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3IZ
  (JNIEnv *, jclass, jintArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([JZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3JZ
  (JNIEnv *, jclass, jlongArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([FZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3FZ
  (JNIEnv *, jclass, jfloatArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    map
 * Signature: ([DZ)Lcom/zekrom_64/ze/nat/ZEArrayMemory;
 */
JNIEXPORT jobject JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_map___3DZ
  (JNIEnv *, jclass, jdoubleArray, jboolean);

/*
 * Class:     com_zekrom_64_ze_nat_ZEArrayMemory
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zekrom_164_ze_nat_ZEArrayMemory_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
